encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
title: "Hai046'blog"
email: haizhu12345@gmail.com
description: Myself blog
url: "http://www.denghaizhu.com" # the base hostname & protocol for your site
github_username:  hai046

